=== SlavaMirolyubov/xml_homework/src/main/java/com/mirolyubov/product.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.example.com"
           elementFormDefault="qualified"
           xmlns="http://www.example.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="products" type="productsType"/>

  <xs:complexType name="productsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="category" type="categoryType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="categoryType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="subcategory" type="subcategoryType"   />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="subcategoryType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="item" type="itemType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="manufacturer" type="xs:string"/>

      <xs:element name="model" >
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]{2}[0-9]{3}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="date_of_manufacture"  >
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0[1-9]|[12][0-9]|3[01])[- \.](0[1-9]|1[012])[- \.](19|20)\d\d" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="color" >
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="price" default="0.0" >
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="amount" default="0" >
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== SlavaMirolyubov/xml_homework/src/main/java/com/mirolyubov/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<products
        xmlns="http://www.example.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.com product.xsd">
    <category name="fridges">
        <subcategory name="twinCam">
            <item>
                <manufacturer>Samsung</manufacturer>
                <model>GL123</model>
                <date_of_manufacture>23-10-2018</date_of_manufacture>
                <color>White</color>
                <price>18500</price>
                <amount>4</amount>
            </item>
            <item>
                <manufacturer>LG</manufacturer>
                <model>BC996</model>
                <date_of_manufacture>29-02-2016</date_of_manufacture>
                <color>Gray</color>
                <price>16385</price>
                <amount>2</amount>
            </item>
        </subcategory>
        <subcategory name="oneCam">
            <item>
                <manufacturer>Bosh</manufacturer>
                <model>JA349</model>
                <date_of_manufacture>04-06-2012</date_of_manufacture>
                <color>Silver</color>
                <price>15000</price>
                <amount>17</amount>
            </item>
            <item>
                <manufacturer>Hitachi</manufacturer>
                <model>SV896</model>
                <date_of_manufacture>29-07-2008</date_of_manufacture>
                <color>Dark_gray</color>
                <price>434.78</price>
                <amount>22</amount>
            </item>
        </subcategory>
    </category>
    <category name="stove">
        <subcategory name="embed">
            <item>
                <manufacturer>Bosh</manufacturer>
                <model>AP980</model>
                <date_of_manufacture>23-11-2014</date_of_manufacture>
                <color>Black</color>
                <price>17500</price>
                <amount>1</amount>
            </item>
            <item>
                <manufacturer>Gas</manufacturer>
                <model>KO156</model>
                <date_of_manufacture>28-02-2017</date_of_manufacture>
                <color>Silver</color>
                <price>20000</price>
                <amount>87</amount>
            </item>
        </subcategory>
    </category>
</products>
